services:
  # --- INFRASTRUCTURE ---
  mongo:
    image: mongo:latest
    container_name: chef-mongo
    ports:
      - "27017:27017"
    networks:
      - chef-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: chef-rabbitmq
    ports:
      - "5672:5672"     
      - "15672:15672"   
    networks:
      - chef-network

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: chef-keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8081:8080"
    networks:
      - chef-network

  # --- MICROSERVICIOS ---

  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "8001:8000"
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://mongo:27017/chefmatch
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - SESSION_SECRET=${SESSION_SECRET}
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=ChefMatchRealm
      - KEYCLOAK_CLIENT_ID=account
    depends_on:
      - mongo
      - rabbitmq
      - keycloak
    networks:
      - chef-network

  recipe-service:
    build: ./services/recipe-service
    container_name: recipe-service
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://mongo:27017/chefmatch
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=ChefMatchRealm
      - KEYCLOAK_CLIENT_ID=account
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - chef-network

  recommendation-service:
    build: ./services/recommendation-service
    container_name: recommendation-service
    ports:
      - "8002:8000"
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://mongo:27017/chefmatch
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=ChefMatchRealm
      - KEYCLOAK_CLIENT_ID=recommendation-service
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_RECOMMENDATION_SECRET}
      - RECIPE_SERVICE_URL=http://recipe-service:8000
    depends_on:
      - mongo
      - rabbitmq
      - recipe-service
    networks:
      - chef-network

networks:
  chef-network:
    driver: bridge
