apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: chefmatch
type: Opaque
stringData:
  # ── RabbitMQ: AMQPS  5671 ──────────────────────────────
  rabbitmq-url: "amqps://admin:admin@rabbitmq-service:5671"

  # ── MongoDB: TLS  ────────────────────────────────────────
  mongo-uri: "mongodb://mongo-service.chefmatch.svc.cluster.local:27017/chefmatch?tls=true"

  # ── Keycloak  ───────────────────────────────────────
  keycloak-url: "https://keycloak.ltu-m7011e-5.se"
  keycloak-realm: "ChefMatchRealm"
  keycloak-client-id: "frontend-client"
  keycloak-recommendation-client-id: "recommendation-service"
  keycloak-recommendation-client-secret: "I0RwWvCJVRHpGUFOEwlxYEvupv8lXKyp"
